version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - darikletter
    labels:
      - "github action"
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: increase
    labels:
      - "npm"
      - "dependencies"
    reviewers:
      - darikletter
    open-pull-requests-limit: 10
